import { MenuItem } from "@/types/menu";

export const MENU_ITEMS: MenuItem[] = [
  {
    name: "Grilled Chicken Salad",
    description:
      "Fresh salad with grilled chicken breast, olive oil, and herbs. Fresh salad with grilled chicken breast, olive oil, and herbs. Fresh salad with grilled chicken breast, olive oil, and herbs. Fresh salad with grilled chicken breast, olive oil, and herbs. Fresh salad with grilled chicken breast, olive oil, and herbs. ",
    plans: ["Diet", "Protein"],
    mealTypes: ["Lunch", "Dinner"],
    nutrition: {
      calories: 320,
      protein: 30,
      fat: 12,
      carbs: 15,
      fiber: 5,
      sugar: 3,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Oatmeal Banana Bowl",
    description: "Warm oats topped with banana slices and chia seeds.",
    plans: ["Diet", "Royal"],
    mealTypes: ["Breakfast"],
    nutrition: {
      calories: 280,
      protein: 8,
      fat: 6,
      carbs: 45,
      fiber: 7,
      sugar: 10,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Beef Teriyaki Quinoa",
    description:
      "Lean beef in teriyaki sauce served with quinoa and steamed veggies.",
    plans: ["Protein", "Royal"],
    mealTypes: ["Lunch", "Dinner"],
    nutrition: {
      calories: 450,
      protein: 35,
      fat: 14,
      carbs: 30,
      fiber: 4,
      sugar: 6,
    },
    allergenFree: false,
    allergenInfo: "Contains soy and sesame.",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Avocado Toast",
    description:
      "Whole grain toast topped with smashed avocado and sesame seeds.",
    plans: ["Diet"],
    mealTypes: ["Breakfast"],
    nutrition: {
      calories: 250,
      protein: 6,
      fat: 14,
      carbs: 22,
      fiber: 6,
      sugar: 2,
    },
    allergenFree: false,
    allergenInfo: "Contains gluten and sesame.",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Protein Pancakes",
    description: "High-protein pancakes with maple syrup and berries.",
    plans: ["Protein"],
    mealTypes: ["Breakfast"],
    nutrition: {
      calories: 350,
      protein: 28,
      fat: 8,
      carbs: 35,
      fiber: 4,
      sugar: 8,
    },
    allergenFree: false,
    allergenInfo: "Contains eggs, dairy, and gluten.",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Veggie Stir Fry",
    description: "Mixed vegetables stir-fried with tofu and light soy sauce.",
    plans: ["Diet", "Royal"],
    mealTypes: ["Lunch", "Dinner"],
    nutrition: {
      calories: 300,
      protein: 12,
      fat: 10,
      carbs: 30,
      fiber: 6,
      sugar: 4,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Baked Salmon",
    description: "Oven-baked salmon served with lemon and brown rice.",
    plans: ["Protein", "Royal"],
    mealTypes: ["Lunch", "Dinner"],
    nutrition: {
      calories: 420,
      protein: 34,
      fat: 18,
      carbs: 20,
      fiber: 3,
      sugar: 1,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Greek Yogurt Parfait",
    description: "Greek yogurt layered with granola and fresh berries.",
    plans: ["Diet", "Royal"],
    mealTypes: ["Breakfast"],
    nutrition: {
      calories: 280,
      protein: 15,
      fat: 5,
      carbs: 30,
      fiber: 3,
      sugar: 12,
    },
    allergenFree: false,
    allergenInfo: "Contains dairy and gluten.",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Tofu Buddha Bowl",
    description: "Brown rice bowl with tofu, avocado, and roasted veggies.",
    plans: ["Diet", "Royal"],
    mealTypes: ["Lunch", "Dinner"],
    nutrition: {
      calories: 350,
      protein: 14,
      fat: 12,
      carbs: 40,
      fiber: 7,
      sugar: 5,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Egg White Omelette",
    description: "Egg white omelette with spinach and mushrooms.",
    plans: ["Diet", "Protein"],
    mealTypes: ["Breakfast"],
    nutrition: {
      calories: 220,
      protein: 18,
      fat: 6,
      carbs: 10,
      fiber: 2,
      sugar: 1,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Chicken Quinoa Bowl",
    description: "Grilled chicken over quinoa with broccoli and tahini sauce.",
    plans: ["Protein", "Royal"],
    mealTypes: ["Lunch"],
    nutrition: {
      calories: 410,
      protein: 32,
      fat: 14,
      carbs: 35,
      fiber: 5,
      sugar: 3,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Fruit Smoothie",
    description: "Mixed berry smoothie with almond milk and flaxseed.",
    plans: ["Diet", "Royal"],
    mealTypes: ["Breakfast"],
    nutrition: {
      calories: 190,
      protein: 5,
      fat: 4,
      carbs: 28,
      fiber: 4,
      sugar: 18,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Turkey Wrap",
    description: "Whole wheat wrap with turkey, lettuce, and hummus.",
    plans: ["Protein"],
    mealTypes: ["Lunch"],
    nutrition: {
      calories: 330,
      protein: 24,
      fat: 10,
      carbs: 28,
      fiber: 3,
      sugar: 2,
    },
    allergenFree: false,
    allergenInfo: "Contains gluten and sesame.",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Zucchini Noodles",
    description: "Spiralized zucchini with tomato sauce and grilled shrimp.",
    plans: ["Diet", "Royal"],
    mealTypes: ["Dinner"],
    nutrition: {
      calories: 310,
      protein: 26,
      fat: 9,
      carbs: 18,
      fiber: 4,
      sugar: 5,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Lentil Soup",
    description: "Hearty soup made with lentils, carrots, and spices.",
    plans: ["Diet"],
    mealTypes: ["Lunch", "Dinner"],
    nutrition: {
      calories: 290,
      protein: 14,
      fat: 6,
      carbs: 36,
      fiber: 8,
      sugar: 3,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Chia Pudding",
    description: "Coconut milk chia pudding topped with mango slices.",
    plans: ["Diet", "Royal"],
    mealTypes: ["Breakfast"],
    nutrition: {
      calories: 240,
      protein: 6,
      fat: 10,
      carbs: 25,
      fiber: 6,
      sugar: 7,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Steak & Broccoli",
    description: "Lean grilled steak with steamed broccoli and sweet potatoes.",
    plans: ["Protein", "Royal"],
    mealTypes: ["Dinner"],
    nutrition: {
      calories: 480,
      protein: 36,
      fat: 20,
      carbs: 28,
      fiber: 4,
      sugar: 2,
    },
    allergenFree: false,
    allergenInfo: "May contain soy marinade.",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Tofu Scramble",
    description:
      "Crumbled tofu sautéed with turmeric, bell peppers, and spinach.",
    plans: ["Diet"],
    mealTypes: ["Breakfast"],
    nutrition: {
      calories: 260,
      protein: 13,
      fat: 10,
      carbs: 18,
      fiber: 5,
      sugar: 2,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Chicken Caesar Wrap",
    description: "Grilled chicken with romaine, Caesar dressing, in a wrap.",
    plans: ["Protein", "Royal"],
    mealTypes: ["Lunch"],
    nutrition: {
      calories: 400,
      protein: 30,
      fat: 16,
      carbs: 30,
      fiber: 3,
      sugar: 2,
    },
    allergenFree: false,
    allergenInfo: "Contains gluten, dairy, and anchovy.",
    image: "/menu-placeholder.jpg",
  },
  {
    name: "Sweet Potato & Black Bean Bowl",
    description: "Roasted sweet potato, black beans, and avocado.",
    plans: ["Diet", "Royal"],
    mealTypes: ["Lunch", "Dinner"],
    nutrition: {
      calories: 350,
      protein: 12,
      fat: 11,
      carbs: 45,
      fiber: 9,
      sugar: 5,
    },
    allergenFree: true,
    allergenInfo: "",
    image: "/menu-placeholder.jpg",
  },
];
